<?php
// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

// Load the view framework
if(!class_exists('VmView'))require(VMPATH_SITE.DS.'helpers'.DS.'vmview.php');

class VirtuemartViewAndroid extends VmView {

var $jsonInput;
var $jsonOutput;
var $jsonStructure;
var $intentModel;
var $currentUser;
var $intentId;

    public function display($tpl = null) {
    require_once JPATH_BASE.'/components/com_slogin/controller.php';
    $slogin = new SLoginController();
    JFactory::getApplication()->input->setString("plugin", "vkontakte");
    $slogin->check();
    $this->setLayout('default');
    $this->model = VmModel::getModel('sources');

    $this->currentUser = JFactory::getUser();
    $this->jsonInput=json_decode(vRequest::getCmd("data", ""));

    $action=vRequest::getCmd("action", "");
    $token=vRequest::getCmd("token", "");
    //$action=vRequest::getCmd("action", "");
    $this->jsonOutput=new stdClass();


    if(is_callable(array($this->model, $action))) $this->jsonOutput=$this->model->$action();
    //echo "hi";


 return parent::display($tpl); // TODO: Change the autogenerated stub
}

}
?>