<?php
// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

// Load the view framework
if(!class_exists('VmView'))require(VMPATH_SITE.DS.'helpers'.DS.'vmview.php');

class VirtuemartViewAjax extends VmView {

var $jsonInput;
var $jsonOutput;
var $jsonStructure;
var $intentModel;
var $currentUser;
var $intentId;

    public function display($tpl = null) {

    $this->setLayout('json');
    $object=vRequest::getCmd("model", "");
    $this->model = VmModel::getModel('intent');
    $this->currentUser = JFactory::getUser();
    $this->jsonInput=json_decode(vRequest::getCmd("data", ""));

    $object=vRequest::getCmd("object", "");
    //$action=vRequest::getCmd("action", "");
    $this->jsonOutput=new stdClass();


    if(is_callable(array($this->model, $object))) $this->jsonOutput=$this->model->$object();
    //echo "hi";


 return parent::display($tpl); // TODO: Change the autogenerated stub
}

}
?>