<?php
// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

// Load the view framework
if(!class_exists('VmView'))require(VMPATH_SITE.DS.'helpers'.DS.'vmview.php');
if(!class_exists('WxModel')) require(VMPATH_SITE.DS. 'helpers' .DS. 'wxmodel.php');

class VirtuemartViewAjax extends VmView {

var $jsonInput;
var $jsonOutput;
var $jsonStructure;
var $intentModel;
var $currentUser;
var $intentId;

    public function display($tpl = null) {

    $this->setLayout('json');
    $object=vRequest::getCmd("model", "sources");
    if($object=="sources")
        $this->model = VmModel::getModel($object);
    else
        $this->model = WxModel::getModel($object);
    $this->currentUser = JFactory::getUser();
    $this->jsonInput=json_decode(vRequest::getCmd("data", ""));

    $action=vRequest::getCmd("action", "");

    $this->jsonOutput=new stdClass();


    if(is_callable(array($this->model, $action))) $this->jsonOutput=$this->model->$action();
    //echo "hi";


 return parent::display($tpl); // TODO: Change the autogenerated stub
}

}
?>